[package]
name = "app-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui_extras = { version = "0.27.2", features = ["image", "svg"] }
image = { version = "0.24", default-features = false, features = ["png"] }
walkdir = "2.3"
fuzzy-matcher = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
linicon = "2.3"
dirs = "5.0"
