---@type Base46Theme
-- lua/themes/minimal.lua — Base46 theme for NvChad
-- Generated by minimalctl — DO NOT edit directly.

local M = {}

M.base_30 = {
  white         = "#E8EDF5",
  darker_black  = "#0B0E14",
  black         = "#0B0E14",
  black2        = "#11161F",
  one_bg        = "#11161F",
  one_bg2       = "#19212D",
  one_bg3       = "#19212D",
  grey          = "#7F899B",
  grey_fg       = "#7F899B",
  grey_fg2      = "#7F899B",
  light_grey    = "#7F899B",
  red           = "#F08080",
  baby_pink     = "#F08080",
  pink          = "#B4A7FF",
  line          = "#19212D",
  green         = "#8BE28B",
  vibrant_green = "#8BE28B",
  nord_blue     = "#8BA4FF",
  blue          = "#8BA4FF",
  yellow        = "#E8C77B",
  sun           = "#E8C77B",
  purple        = "#B4A7FF",
  dark_purple   = "#B4A7FF",
  teal          = "#7DD3FC",
  orange        = "#E8C77B",
  cyan          = "#7DD3FC",
  statusline_bg = "#11161F",
  lightbg       = "#19212D",
  pmenu_bg      = "#7DD3FC",
  folder_bg     = "#8BA4FF",
}

M.base_16 = {
  base00 = "#0B0E14",
  base01 = "#11161F",
  base02 = "#19212D",
  base03 = "#7F899B",
  base04 = "#7F899B",
  base05 = "#E8EDF5",
  base06 = "#E8EDF5",
  base07 = "#E8EDF5",
  base08 = "#F08080",
  base09 = "#E8C77B",
  base0A = "#E8C77B",
  base0B = "#8BE28B",
  base0C = "#7DD3FC",
  base0D = "#8BA4FF",
  base0E = "#B4A7FF",
  base0F = "#F08080",
}

M.type = "dark"

return M
